-- Curated playlist tables for the public Curated Playlists page and admin Playlist Manager.
create table if not exists public.curated_playlist_groups (
  id bigint generated by default as identity primary key,
  name text not null unique,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.curated_playlist_groups (name, position)
values
  ('Editor Picks', 0),
  ('Documentary', 1),
  ('Commercial', 2),
  ('Travel', 3),
  ('Tension', 4),
  ('Ambient', 5)
on conflict (name) do nothing;

create table if not exists public.curated_playlists (
  id bigint generated by default as identity primary key,
  name text not null,
  kicker text not null default 'Curated selection',
  cover_image_url text,
  playlist_group text not null default 'Editor Picks',
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.curated_playlist_songs (
  id bigint generated by default as identity primary key,
  curated_playlist_id bigint not null references public.curated_playlists(id) on delete cascade,
  song_id text not null references public.songs(id) on delete cascade,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  unique (curated_playlist_id, song_id)
);

create index if not exists curated_playlists_group_position_idx
  on public.curated_playlists (playlist_group, position);

create index if not exists curated_playlist_songs_playlist_position_idx
  on public.curated_playlist_songs (curated_playlist_id, position);

create index if not exists curated_playlist_songs_song_id_idx
  on public.curated_playlist_songs (song_id);

create index if not exists curated_playlist_groups_position_idx
  on public.curated_playlist_groups (position);
