-- Curated playlist tables for the public Curated Playlists page and admin Playlist Manager.
create table if not exists public.curated_playlists (
  id bigint generated by default as identity primary key,
  name text not null,
  kicker text not null default 'Curated selection',
  cover_image_url text,
  playlist_group text not null default 'Editor Picks',
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.curated_playlist_songs (
  id bigint generated by default as identity primary key,
  curated_playlist_id bigint not null references public.curated_playlists(id) on delete cascade,
  song_id text not null references public.songs(id) on delete cascade,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  unique (curated_playlist_id, song_id)
);

create index if not exists curated_playlists_group_position_idx
  on public.curated_playlists (playlist_group, position);

create index if not exists curated_playlist_songs_playlist_position_idx
  on public.curated_playlist_songs (curated_playlist_id, position);

create index if not exists curated_playlist_songs_song_id_idx
  on public.curated_playlist_songs (song_id);

-- Discover page management fields.
alter table public.curated_playlists
  add column if not exists description text not null default '',
  add column if not exists discover_section text,
  add column if not exists show_on_discover boolean not null default false,
  add column if not exists discover_position integer not null default 0;

create index if not exists curated_playlists_discover_section_position_idx
  on public.curated_playlists (discover_section, discover_position);

create index if not exists curated_playlists_show_on_discover_position_idx
  on public.curated_playlists (show_on_discover, discover_position)
  where show_on_discover = true;
