-- Playlist shelf memberships let one curated playlist appear in multiple manual shelves.
create table if not exists public.curated_playlist_shelf_items (
  id bigint generated by default as identity primary key,
  shelf_key text not null check (shelf_key in ('popular', 'trending')),
  curated_playlist_id bigint not null references public.curated_playlists(id) on delete cascade,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  unique (shelf_key, curated_playlist_id)
);

create index if not exists curated_playlist_shelf_items_shelf_position_idx
  on public.curated_playlist_shelf_items (shelf_key, position);

-- Preserve the current manually curated shelves as the initial shelf memberships.
insert into public.curated_playlist_shelf_items (
  shelf_key,
  curated_playlist_id,
  position
)
select
  'popular',
  id,
  position
from public.curated_playlists
where playlist_group = 'Popular Right Now'
on conflict (shelf_key, curated_playlist_id) do nothing;

insert into public.curated_playlist_shelf_items (
  shelf_key,
  curated_playlist_id,
  position
)
select
  'trending',
  id,
  position
from public.curated_playlists
where playlist_group = 'Trending Playlists'
on conflict (shelf_key, curated_playlist_id) do nothing;
