create table if not exists public.discover_featured_artists (
  id bigint generated by default as identity primary key,
  artist_id uuid not null references public.artists(id) on delete cascade,
  position integer not null default 0 check (position >= 0),
  created_at timestamptz not null default now(),
  constraint discover_featured_artists_artist_id_key unique (artist_id)
);

create index if not exists discover_featured_artists_position_idx
  on public.discover_featured_artists (position);

alter table public.discover_featured_artists enable row level security;
