delete from public.curated_playlist_shelf_items
where shelf_key = 'discover_feature_cards';

alter table public.curated_playlist_shelf_items
  drop constraint if exists curated_playlist_shelf_items_shelf_key_check;

alter table public.curated_playlist_shelf_items
  add constraint curated_playlist_shelf_items_shelf_key_check
  check (
    shelf_key = any (
      array[
        'popular'::text,
        'trending'::text,
        'discover_moods'::text,
        'discover_curated'::text,
        'discover_production'::text
      ]
    )
  );

create table if not exists public.discover_feature_card_artists (
  id bigint generated by default as identity primary key,
  artist_id uuid not null references public.artists(id) on delete cascade,
  position integer not null default 0 check (position >= 0),
  created_at timestamptz not null default now(),
  constraint discover_feature_card_artists_artist_id_key unique (artist_id)
);

create index if not exists discover_feature_card_artists_position_idx
  on public.discover_feature_card_artists (position);

alter table public.discover_feature_card_artists enable row level security;

grant select, insert, update, delete on table public.discover_feature_card_artists to service_role;
grant usage, select on sequence public.discover_feature_card_artists_id_seq to service_role;
