create table if not exists public.curated_browse_subcategories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  label text not null,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  constraint curated_browse_subcategories_slug_check
    check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint curated_browse_subcategories_label_check
    check (length(btrim(label)) > 0)
);

create table if not exists public.curated_browse_filter_subcategories (
  browse_filter text not null,
  subcategory_id bigint not null references public.curated_browse_subcategories(id) on delete cascade,
  position integer not null default 0,
  primary key (browse_filter, subcategory_id),
  constraint curated_browse_filter_subcategories_filter_check
    check (browse_filter in ('editors', 'mood', 'genre', 'brands', 'travel', 'documentary', 'cinematic', 'dark-moody'))
);

create table if not exists public.curated_playlist_browse_assignments (
  curated_playlist_id bigint not null references public.curated_playlists(id) on delete cascade,
  browse_filter text not null,
  subcategory_id bigint not null,
  primary key (curated_playlist_id, browse_filter, subcategory_id),
  constraint curated_playlist_browse_assignments_filter_check
    check (browse_filter in ('editors', 'mood', 'genre', 'brands', 'travel', 'documentary', 'cinematic', 'dark-moody')),
  constraint curated_playlist_browse_assignments_taxonomy_fkey
    foreign key (browse_filter, subcategory_id)
    references public.curated_browse_filter_subcategories(browse_filter, subcategory_id)
    on delete cascade
);

create index if not exists curated_browse_filter_subcategories_subcategory_idx
  on public.curated_browse_filter_subcategories(subcategory_id);

create index if not exists curated_playlist_browse_assignments_filter_subcategory_idx
  on public.curated_playlist_browse_assignments(browse_filter, subcategory_id);

alter table public.curated_browse_subcategories enable row level security;
alter table public.curated_browse_filter_subcategories enable row level security;
alter table public.curated_playlist_browse_assignments enable row level security;

grant select, insert, update, delete on table public.curated_browse_subcategories to service_role;
grant select, insert, update, delete on table public.curated_browse_filter_subcategories to service_role;
grant select, insert, update, delete on table public.curated_playlist_browse_assignments to service_role;
grant usage, select on sequence public.curated_browse_subcategories_id_seq to service_role;

insert into public.curated_browse_subcategories (slug, label, position)
values
  ('brand-commercial', 'Brand & Commercial', 0),
  ('youtube-creator', 'YouTube & Creator', 1),
  ('educational-explainer', 'Educational & Explainer', 2),
  ('travel', 'Travel', 3),
  ('documentary', 'Documentary', 4),
  ('product-tech', 'Product & Tech', 5),
  ('film-story', 'Film & Story', 6),
  ('lifestyle', 'Lifestyle', 7),
  ('uplifting', 'Uplifting', 8),
  ('emotional', 'Emotional', 9),
  ('reflective', 'Reflective', 10),
  ('energetic', 'Energetic', 11),
  ('playful', 'Playful', 12),
  ('calm', 'Calm', 13),
  ('tense', 'Tense', 14),
  ('dark', 'Dark', 15),
  ('cinematic', 'Cinematic', 16),
  ('corporate', 'Corporate', 17),
  ('world', 'World', 18),
  ('background', 'Background', 19),
  ('tech-innovation', 'Tech & Innovation', 20),
  ('advertising', 'Advertising', 21),
  ('brand-lifestyle', 'Brand & Lifestyle', 22),
  ('food-hospitality', 'Food & Hospitality', 23),
  ('luxury', 'Luxury', 24),
  ('sports-fitness', 'Sports & Fitness', 25),
  ('product', 'Product', 26),
  ('adventure', 'Adventure', 27),
  ('road-trip', 'Road Trip', 28),
  ('coastal', 'Coastal', 29),
  ('desert', 'Desert', 30),
  ('mountain', 'Mountain', 31),
  ('city', 'City', 32),
  ('slow-travel', 'Slow Travel', 33),
  ('human-stories', 'Human Stories', 34),
  ('educational', 'Educational', 35),
  ('nature', 'Nature', 36),
  ('history', 'History', 37),
  ('science-technology', 'Science & Technology', 38),
  ('culture-travel', 'Culture & Travel', 39),
  ('social-impact', 'Social Impact', 40),
  ('sports', 'Sports', 41),
  ('epic-trailer', 'Epic & Trailer', 42),
  ('emotional-storytelling', 'Emotional Storytelling', 43),
  ('intimate', 'Intimate', 44),
  ('atmospheric', 'Atmospheric', 45),
  ('action', 'Action', 46),
  ('suspense', 'Suspense', 47),
  ('wonder-discovery', 'Wonder & Discovery', 48),
  ('minimal-cinematic', 'Minimal Cinematic', 49),
  ('brooding', 'Brooding', 50),
  ('mystery', 'Mystery', 51),
  ('uneasy', 'Uneasy', 52),
  ('gritty', 'Gritty', 53),
  ('noir', 'Noir', 54),
  ('industrial', 'Industrial', 55),
  ('slow-burn', 'Slow Burn', 56)
on conflict (slug) do update
set label = excluded.label,
    position = excluded.position;

with mappings(browse_filter, slug, position) as (
  values
    ('editors', 'brand-commercial', 0),
    ('editors', 'youtube-creator', 1),
    ('editors', 'educational-explainer', 2),
    ('editors', 'travel', 3),
    ('editors', 'documentary', 4),
    ('editors', 'product-tech', 5),
    ('editors', 'film-story', 6),
    ('editors', 'lifestyle', 7),
    ('mood', 'uplifting', 0),
    ('mood', 'emotional', 1),
    ('mood', 'reflective', 2),
    ('mood', 'energetic', 3),
    ('mood', 'playful', 4),
    ('mood', 'calm', 5),
    ('mood', 'tense', 6),
    ('mood', 'dark', 7),
    ('genre', 'cinematic', 0),
    ('genre', 'corporate', 1),
    ('genre', 'documentary', 2),
    ('genre', 'youtube-creator', 3),
    ('genre', 'world', 4),
    ('genre', 'background', 5),
    ('genre', 'tech-innovation', 6),
    ('genre', 'advertising', 7),
    ('genre', 'brand-lifestyle', 8),
    ('brands', 'lifestyle', 0),
    ('brands', 'corporate', 1),
    ('brands', 'tech-innovation', 2),
    ('brands', 'food-hospitality', 3),
    ('brands', 'luxury', 4),
    ('brands', 'sports-fitness', 5),
    ('brands', 'product', 6),
    ('travel', 'adventure', 0),
    ('travel', 'road-trip', 1),
    ('travel', 'world', 2),
    ('travel', 'coastal', 3),
    ('travel', 'desert', 4),
    ('travel', 'mountain', 5),
    ('travel', 'city', 6),
    ('travel', 'slow-travel', 7),
    ('documentary', 'human-stories', 0),
    ('documentary', 'educational', 1),
    ('documentary', 'nature', 2),
    ('documentary', 'history', 3),
    ('documentary', 'science-technology', 4),
    ('documentary', 'culture-travel', 5),
    ('documentary', 'social-impact', 6),
    ('documentary', 'sports', 7),
    ('cinematic', 'epic-trailer', 0),
    ('cinematic', 'emotional-storytelling', 1),
    ('cinematic', 'intimate', 2),
    ('cinematic', 'atmospheric', 3),
    ('cinematic', 'action', 4),
    ('cinematic', 'suspense', 5),
    ('cinematic', 'wonder-discovery', 6),
    ('cinematic', 'minimal-cinematic', 7),
    ('dark-moody', 'brooding', 0),
    ('dark-moody', 'mystery', 1),
    ('dark-moody', 'suspense', 2),
    ('dark-moody', 'uneasy', 3),
    ('dark-moody', 'gritty', 4),
    ('dark-moody', 'noir', 5),
    ('dark-moody', 'industrial', 6),
    ('dark-moody', 'slow-burn', 7)
)
insert into public.curated_browse_filter_subcategories (browse_filter, subcategory_id, position)
select mappings.browse_filter, subcategory.id, mappings.position
from mappings
join public.curated_browse_subcategories as subcategory
  on subcategory.slug = mappings.slug
on conflict (browse_filter, subcategory_id) do update
set position = excluded.position;

with legacy_values as (
  select
    playlist.id as curated_playlist_id,
    playlist.browse_tags,
    item.value as raw_value,
    case
      when item.value = 'editors:social-short-form' then 'film-story'
      when position(':' in item.value) > 0 then split_part(item.value, ':', 2)
      else item.value
    end as slug,
    case
      when position(':' in item.value) > 0 then split_part(item.value, ':', 1)
      else null
    end as legacy_filter
  from public.curated_playlists as playlist
  cross join lateral unnest(playlist.browse_subcategories) as item(value)
)
insert into public.curated_playlist_browse_assignments (
  curated_playlist_id,
  browse_filter,
  subcategory_id
)
select distinct
  legacy.curated_playlist_id,
  mapping.browse_filter,
  subcategory.id
from legacy_values as legacy
join public.curated_browse_subcategories as subcategory
  on subcategory.slug = legacy.slug
join public.curated_browse_filter_subcategories as mapping
  on mapping.subcategory_id = subcategory.id
 and (
   (legacy.legacy_filter is not null and mapping.browse_filter = legacy.legacy_filter)
   or
   (legacy.legacy_filter is null and mapping.browse_filter = any(legacy.browse_tags))
 )
on conflict do nothing;
