"use client";

import { useEffect } from "react";
import { createRoot, type Root } from "react-dom/client";
import Link from "next/link";

type AdminSongFormEditPointsLinkInjectorProps = {
  songId: string;
};

const EDIT_POINTS_HELPER_TEXT =
  "Edit point data is generated by the analyzer and can be reviewed in the waveform editor. You can still inspect or clear the raw JSON here when needed.";

function EditPointsHeaderButton({ songId }: AdminSongFormEditPointsLinkInjectorProps) {
  return (
    <Link
      href={`/admin/songs/${songId}/edit-points?from=edit-details`}
      className="inline-flex h-7 items-center rounded-full border border-[var(--border)] px-3 text-[11px] font-medium text-[var(--text-secondary)] transition hover:bg-[var(--bg-hover)] hover:text-[var(--text-primary)]"
    >
      Manage Edit Points
    </Link>
  );
}

export default function AdminSongFormEditPointsLinkInjector({
  songId,
}: AdminSongFormEditPointsLinkInjectorProps) {
  useEffect(() => {
    let root: Root | null = null;
    let target: HTMLDivElement | null = null;
    let mounted = true;

    const findEditPointsHeader = () => {
      const headers = Array.from(
        document.querySelectorAll<HTMLElement>(".admin-song-form-card-header"),
      );

      return headers.find((header) =>
        header.textContent?.trim().toLowerCase().includes("edit points"),
      );
    };

    const updateHelperText = (header: HTMLElement) => {
      const section = header.closest("section");
      const paragraphs = Array.from(section?.querySelectorAll("p") ?? []);
      const helper = paragraphs.find((paragraph) =>
        paragraph.textContent?.toLowerCase().includes("temporary manual json field"),
      );

      if (helper) {
        helper.textContent = EDIT_POINTS_HELPER_TEXT;
      }
    };

    const inject = () => {
      if (!mounted) return false;

      const editPointsHeader = findEditPointsHeader();

      if (!editPointsHeader) return false;

      updateHelperText(editPointsHeader);

      if (editPointsHeader.querySelector("[data-edit-points-editor-link]")) {
        return true;
      }

      target = document.createElement("div");
      target.dataset.editPointsEditorLink = "true";
      target.className = "flex items-center";
      editPointsHeader.appendChild(target);

      root = createRoot(target);
      root.render(<EditPointsHeaderButton songId={songId} />);
      return true;
    };

    const observer = new MutationObserver(() => {
      inject();
    });

    observer.observe(document.body, {
      childList: true,
      subtree: true,
    });

    inject();

    return () => {
      mounted = false;
      observer.disconnect();
      root?.unmount();
      target?.remove();
    };
  }, [songId]);

  return null;
}
